#!/bin/sh
# Copyright (C) 2000-2014 Synology Inc.	All rights reserved.
DirName=/usr/bin/dirname
ReadLink=/bin/readlink
if [ -L $0 ]; then
	RealScript=`${ReadLink} $0`
	ScriptDir=`${DirName} ${RealScript}`
else
	ScriptDir=`${DirName} $0`
fi

LD_LIBRARY_PATH=${ScriptDir}/lib
export LD_LIBRARY_PATH
${ScriptDir}/SynologyAssistant.bin $*

